
const columns = [
  {name: "ID", iid: "id"},
  {name: "NAME", iid: "name"},
  {name: "TITLE", iid: "title"},
  {name: "TIME", iid: "time"},
  {name: "STATUS", iid: "status"},
  {name: "ACTIONS", iid: "actions"},
];

const statusOptions = [
  {name: "已通过", iid: "passed"},
  {name: "未通过", iid: "failed"},
  {name: "待审核", iid: "checking"},
];

const users = [
  {
    id: 0,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 1,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 2,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 3,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 4,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'failed',
  },
  {
    id: 5,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 6,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 7,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'failed',
  },
  {
    id: 8,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 9,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 10,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 11,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 12,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 13,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'failed',
  },
  {
    id: 14,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 15,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 16,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 17,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 18,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 19,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
  {
    id: 20,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'failed',
  },
  {
    id: 21,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 22,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'checking',
  },
  {
    id: 23,
    name: 'nich',
    title: 'title',
    time: '2024-4-1',
    status: 'passed',
  },
];

export {columns, users, statusOptions};
