const express = require('express');
const { prefix, travelDiary_urls, moderationPlatform_urls } = require('../config/InterfaceURL');
const { login } = require('../controllers/travelDiary/login');
const { getUserInfo } = require('../controllers/travelDiary/getUserInfo');
const { setAvatar } = require('../controllers/travelDiary/setAvatar');
const { setNickname } = require('../controllers/travelDiary/setNickname');
const { getNoteListByTime } = require('../controllers/travelDiary/getNoteListByTime');
const { getNoteListBySearchTitle } = require('../controllers/travelDiary/getNoteListBySearchTitle');
const { getNoteListBySearchAuthor } = require('../controllers/travelDiary/getNoteListBySearchAuthor');
const { getNoteDetails } = require('../controllers/travelDiary/getNoteDetails');
const { getNoteComments } = require('../controllers/travelDiary/getNoteComments');
const { likeNote } = require('../controllers/travelDiary/likeNote');
const { collectNote } = require('../controllers/travelDiary/collectNote');
const { cancelCollectNote } = require('../controllers/travelDiary/cancelCollectNote');
const { makeComments } = require('../controllers/travelDiary/makeComment');
const { uploadNote } = require('../controllers/travelDiary/uploadNote');
const { modifyNote } = require('../controllers/travelDiary/modifyNote');
const { deleteNote } = require('../controllers/travelDiary/deleteNote');
const { getMyCollect } = require('../controllers/travelDiary/getMyCollect');
const { getMyNoteListWithStatus } = require('../controllers/travelDiary/getMyNoteListWithStatus');

const travelDiaryRouter = express.Router();

travelDiaryRouter.post(travelDiary_urls.login, login);
travelDiaryRouter.get(travelDiary_urls.getUserInfo, getUserInfo);
travelDiaryRouter.post(travelDiary_urls.setAvatar, setAvatar);
travelDiaryRouter.post(travelDiary_urls.setNickName, setNickname);
travelDiaryRouter.post(travelDiary_urls.getNoteListByTime, getNoteListByTime);
travelDiaryRouter.post(travelDiary_urls.getNoteListBySearchTitle, getNoteListBySearchTitle);
travelDiaryRouter.post(travelDiary_urls.getNoteListBySearchAuthor, getNoteListBySearchAuthor);
travelDiaryRouter.get(travelDiary_urls.getNoteDetails, getNoteDetails);
travelDiaryRouter.get(travelDiary_urls.getNoteComments, getNoteComments);
travelDiaryRouter.get(travelDiary_urls.likeNote, likeNote);
travelDiaryRouter.get(travelDiary_urls.collectNote, collectNote);
travelDiaryRouter.get(travelDiary_urls.cancelCollectNote, cancelCollectNote);
travelDiaryRouter.post(travelDiary_urls.makeComment, makeComments);
travelDiaryRouter.post(travelDiary_urls.uploadNote, uploadNote);
travelDiaryRouter.post(travelDiary_urls.modifyNote, modifyNote);
travelDiaryRouter.post(travelDiary_urls.deleteNote, deleteNote);
travelDiaryRouter.get(travelDiary_urls.getMyCollect, getMyCollect);
travelDiaryRouter.get(travelDiary_urls.getMyNoteListWithStatus, getMyNoteListWithStatus);

module.exports = {travelDiaryRouter};